/**
 * МОДУЛЬ: ФОРМИРОВАНИЕ И ПЕЧАТЬ ДОКУМЕНТА
 * Создание окна с документом и отправка на печать
 */

/**
 * Сформировать документ для печати
 * @param {string} text - Текст документа
 */
function generatePrintDocument(text) {
    const lang = loadLanguage();

    if (!text || text.trim() === '') {
        alert(lang === 'en' ? 'Please enter the document text' : 'Введите текст документа');
        return false;
    }

    const printWindow = window.open('', '_blank');
    if (!printWindow) {
        alert(lang === 'en' ? 'Please allow pop-ups for this site' : 'Разрешите всплывающие окна для этого сайта');
        return false;
    }

    const dateStr = new Date().toLocaleString(lang === 'en' ? 'en-US' : 'ru-RU');

    let title, headerText, footerText, printBtnText, closeBtnText;

    if (lang === 'en') {
        title = 'Medical Document';
        headerText = 'Medical Document';
        footerText = 'Generated by MedVoice system';
        printBtnText = 'Print';
        closeBtnText = 'Close';
    } else {
        title = 'Медицинский документ';
        headerText = 'Медицинский документ';
        footerText = 'Сформировано в системе MedVoice';
        printBtnText = 'Распечатать';
        closeBtnText = 'Закрыть';
    }

    const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>${title}</title>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
            <style>
                * {
                    margin: 0;
                    padding: 0;
                    box-sizing: border-box;
                }
                body { 
                    padding: 40px; 
                    font-size: 18px;
                    line-height: 1.6;
                    background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
                    min-height: 100vh;
                }
                .document {
                    max-width: 800px;
                    margin: 0 auto;
                    background: white;
                    padding: 40px;
                    border-radius: 10px;
                    box-shadow: 0 10px 30px rgba(0,0,0,0.1);
                }
                .header {
                    text-align: center;
                    margin-bottom: 30px;
                    border-bottom: 2px solid #667eea;
                    padding-bottom: 20px;
                }
                .header h2 {
                    color: #667eea;
                    margin: 0;
                }
                .content {
                    white-space: pre-wrap;
                    font-family: inherit;
                    margin: 20px 0;
                }
                .footer {
                    margin-top: 30px;
                    text-align: right;
                    color: #666;
                }
                .buttons {
                    text-align: center;
                    margin-top: 30px;
                    display: flex;
                    gap: 15px;
                    justify-content: center;
                    flex-wrap: wrap;
                }
                .btn-print, .btn-close {
                    display: inline-flex;
                    align-items: center;
                    justify-content: center;
                    gap: 8px;
                    padding: 12px 24px;
                    border-radius: 8px;
                    cursor: pointer;
                    font-size: 16px;
                    font-weight: bold;
                    border: none;
                    transition: all 0.3s;
                    line-height: 1;
                    min-width: 140px;
                }
                .btn-print {
                    background: #4a6fa5;
                    color: white;
                }
                .btn-print:hover {
                    background: #5b7fb5;
                    transform: scale(1.02);
                }
                .btn-close {
                    background: #6c757d;
                    color: white;
                }
                .btn-close:hover {
                    background: #5a6268;
                    transform: scale(1.02);
                }
                @media print {
                    body {
                        background: white;
                        padding: 0;
                    }
                    .buttons {
                        display: none;
                    }
                    .document {
                        box-shadow: none;
                        padding: 20px;
                    }
                }
                @media (max-width: 600px) {
                    body {
                        padding: 20px;
                    }
                    .document {
                        padding: 20px;
                    }
                    .buttons {
                        flex-direction: column;
                        gap: 10px;
                    }
                    .btn-print, .btn-close {
                        width: 100%;
                        justify-content: center;
                    }
                }
            </style>
        </head>
        <body>
            <div class="document">
                <div class="header">
                    <h2>📋 ${headerText}</h2>
                    <p>${dateStr}</p>
                </div>
                <div class="content">
                    ${escapeHtml(text).replace(/\n/g, '<br>')}
                </div>
                <hr>
                <div class="footer">
                    <p>${footerText}</p>
                </div>
                <div class="buttons">
                    <button class="btn-print" onclick="window.print();"><i class="fas fa-print"></i> ${printBtnText}</button>
                    <button class="btn-close" onclick="window.close();"><i class="fas fa-times"></i> ${closeBtnText}</button>
                </div>
            </div>
        </body>
        </html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();
    return true;
}

/**
 * Экранирование HTML-символов для безопасности
 * @param {string} str - Исходная строка
 * @returns {string} Экранированная строка
 */
function escapeHtml(str) {
    return str
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
}